# Generated by Django 5.0.7 on 2024-07-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
