# Generated by Django 5.0.7 on 2024-08-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comment_count',
        ),
    ]
