# Generated by Django 5.0.8 on 2024-08-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_comment_count_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='approach',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='massage',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
