# Generated by Django 5.0.6 on 2024-07-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date'], 'verbose_name': 'کانتکت', 'verbose_name_plural': ' کانتکت ها'},
        ),
    ]
